WEB_Assignment_Team4/Controllers/AssignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WEB_Assignment_Team4.DAL;
using WEB_Assignment_Team4.Models;

namespace WEB_Assignment_Team4.Controllers
{
    public class AssignController : Controller
    {
        private JudgeDAL judgeContext = new JudgeDAL();
        private InterestDAL interestContext = new InterestDAL();
        private CompetitionDAL competitionContext = new CompetitionDAL();

        // GET: AssignController
        public ActionResult Index()
        {
            // Stop Accessing the action if not logged in
            //or account not in the "Administrator" role
            if (HttpContext.Session.GetString("Role") == null ||
              (HttpContext.Session.GetString("Role") != "Administrator"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<JudgeAssign> judgeList = judgeContext.GetAllAssignJudges();
            return View(judgeList);
        }

        public ActionResult AllJudges()
        {
            // Stop Accessing the action if not logged in
            //or account not in the "Administrator" role
            if (HttpContext.Session.GetString("Role") == null ||
              (HttpContext.Session.GetString("Role") != "Administrator"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<Judge> judgeList = judgeContext.GetAllJudges();
            return View(judgeList);
        }

        // GET: AssignController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AssignController/Create
        public ActionResult Assign(int? id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Administrator" Role
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Administrator"))
            {
                return RedirectToAction("Index", "Home");
            }
            ViewData["judgeList"] = GetJudges();
            ViewData["competitionList"] = GetCompetition();
            return View();
        }
        private List<Judge> GetJudges()
        {
            List<Judge> judgeList = judgeContext.GetAllJudges();
            judgeList.Insert(0, new Judge
            {
                JudgeID = 0,
                JudgeName = "Select Name"
            });
            return judgeList;
        }
        private List<Competition> GetCompetition()
        {
            List<Competition> competitionList = competitionContext.GetAllCompetition();
            competitionList.Insert(0, new Competition
            {
                CompetitionID = 0,
                Name = "Select Competition"
            });
            return competitionList;
        }
        // POST: AssignController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Assign(JudgeAssign judgeAssign)
        {
            ViewData["judgeList"] = GetJudges();
            ViewData["competitionList"] = GetCompetition();

            try
            {
                judgeAssign.CompetitionID = judgeContext.Assign(judgeAssign);
                TempData["Message"] = "Judge Competition Has been assigned. ";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                //created an error message and store to tempdata 
                TempData["Message"] = "The Form is empty. Fill in the required blank before" +
                                      " assigning the judges to their respective competition.";
                //return to index page to view the interest list and display an message
                return View(judgeAssign);

            }
        }

        // GET: AssignController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AssignController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AssignController/Delete/5
        public ActionResult AssignDelete(int? id)
        {
            //Stop accessing the action if not logged in
            //or account not in the "Administrator" role
            if ((HttpContext.Session.GetString("Role") == null) ||
              (HttpContext.Session.GetString("Role") != "Administrator"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                //Return to the index page, not allowed to edit
                return RedirectToAction("Index");
            }
            JudgeAssign judgeAssign = judgeContext.GetJudgesRole(id.Value);
            if (judgeAssign == null)
            {
                //Return to the index page, not allowed to edit
                return RedirectToAction("Index");
            }

            return View(judgeAssign);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AssignDelete(JudgeAssign judgeAssign,int? id)
        {
            judgeAssign = judgeContext.GetJudgesRole(id.Value);
            //Delete the records from the database
            judgeContext.AssignDelete(judgeAssign.CompetitionID, judgeAssign.JudgeID);
            TempData["Message"] = "Judge Records Deleted Successfully. ";
            return RedirectToAction("Index");
        }
        public ActionResult JudgeDetails(int id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Administrator" role
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Administrator"))
            {
                return RedirectToAction("Index", "Home");
            }
            Judge judge = judgeContext.GetDetails(id);
            JudgeViewModel judgeVM = MapToJudgeVM(judge);
            return View(judgeVM);
        }

        public JudgeViewModel MapToJudgeVM(Judge judge)
        {
            string areaInterestName = "";
            if (judge.AreaInterestID != null)
            {
                List<Interest> interestList = interestContext.GetAllInterest();
                foreach (Interest interest in interestList)
                {
                    if (interest.AreaInterestID == judge.AreaInterestID.Value)
                    {
                        areaInterestName = interest.Name;
                        break;
                    }
                }
            }

            JudgeViewModel competitionVM = new JudgeViewModel
            {
                JudgeID= judge.JudgeID,
                JudgeName = judge.JudgeName,
                Salutation = judge.Salutation,
                AreaInterestName = areaInterestName,
                EmailAddr = judge.EmailAddr,
                Password = judge.Password
            };
            return competitionVM;
        }
    }
}

WEB_Assignment_Team4/Views/Assign/AllJudges.cshtml
@model IEnumerable<WEB_Assignment_Team4.Models.Judge>

@{
    ViewData["Title"] = "AllJudges";
}
<br />
<h3 style="text-align:center">Judges Profile</h3>
<h4 style="text-align:center">Here you can view the details of the judges profile</h4>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JudgeID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JudgeName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.JudgeID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JudgeName)
            </td>
            <td>
                <a asp-action="JudgeDetails" asp-controller="Assign"
                   asp-route-id="@item.JudgeID">View</a> 
            </td>
        </tr>
}
    </tbody>
</table>

WEB_Assignment_Team4/Views/Assign/Assign.cshtml
@model WEB_Assignment_Team4.Models.JudgeAssign

@{
    ViewData["Title"] = "Assign Judges Roles";
}

<h1>Assign Competition</h1>

<h4>Here you can assign judges to their respective competition</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Assign">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JudgeID" class="control-label"></label>
                <select asp-for="JudgeID"
                        asp-items="@(new SelectList(
                                   ViewData["judgeList"] as List <Judge>,
                                   "JudgeID","JudgeName"))"
                                   class="form-control" required></select>
                <span asp-validation-for="JudgeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompetitionID" class="control-label"></label>
                <select asp-for="CompetitionID"
                        asp-items="@(new SelectList(
                                   ViewData["competitionList"] as List <Competition>,
                                   "CompetitionID","Name"))"
                        class="form-control" required></select>
                <span asp-validation-for="CompetitionID" class="text-danger"></span>
                <br />
                <span style="color:red  ;">@TempData["Message"]</span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WEB_Assignment_Team4/Views/Assign/AssignDelete.cshtml
@model WEB_Assignment_Team4.Models.JudgeAssign

@{
    ViewData["Title"] = "AssignDelete";
}

<h1>AssignDelete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>JudgeAssign</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompetitionID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompetitionID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JudgeID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JudgeID)
        </dd>
    </dl>
    
    <form asp-action="AssignDelete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WEB_Assignment_Team4/Views/Assign/Create.cshtml
@model WEB_Assignment_Team4.Models.JudgeAssign

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>JudgeAssign</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JudgeID" class="control-label"></label>
                <select asp-for="JudgeID"
                        asp-items="@(new SelectList(
                                   ViewData["judgeList"] as List <Judge>,
                                   "JudgeID","JudgeName"))"
                                   class="form-control" required></select>
                <span asp-validation-for="JudgeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompetitionID" class="control-label"></label>
                <select asp-for="CompetitionID"
                        asp-items="@(new SelectList(
                                   ViewData["competitionList"] as List <Competition>,
                                   "CompetitionID","Name"))"
                        class="form-control" required></select>
                <span asp-validation-for="CompetitionID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WEB_Assignment_Team4/Views/Assign/Index.cshtml
@model IEnumerable<WEB_Assignment_Team4.Models.JudgeAssign>

@{
    ViewData["Title"] = "Judge List";
}
<br />
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width = device-width,
                                           initial-scale = 1" />
    <style>
        .title {
            margin-top: 10px;
            text-align: center;
        }
        .title h4{
            font-weight:normal;
        }
        .p{
            margin-top:10px;
        }
    </style>
</head>
<body>
    <div class="title">
        <h2>Assigned Judge Competition List </h2>
        <h4>Here you can assign at least 2 Judges to their respective competition</h4>
        <hr />
    </div>
    <p>
        <a asp-action="Assign">Assign Competition</a>
    </p>
    <span style="color:red  ;">@TempData["Message"]</span>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CompetitionID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.JudgeID)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CompetitionID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.JudgeID)
                    </td>
                    <td>
                        <a asp-action="AssignDelete" asp-controller="Assign"
                           asp-route-id="@item.CompetitionID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

WEB_Assignment_Team4/Views/Assign/JudgeDetails.cshtml
@model WEB_Assignment_Team4.Models.JudgeViewModel

@{
    ViewData["Title"] = "JudgeDetails";
}
<br />
<h3>Judge Profile</h3>
<h4>Here you can view the details of the judge</h4>
<hr />
<div>
    <br />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JudgeID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JudgeID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JudgeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JudgeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AreaInterestName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AreaInterestName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>